version: '3.3'

services:
  dizquetv:
    image: kookster310/dizquetv-arm64:latest
    hostname: dizquetv
    restart: always
    volumes:
      - dizquetv:/opt/dizquetv
    ports:
      - '8000:8000'

  tvtv2xmltv:
    image: nginx:latest
    hostname: tvtv2xmltv
    restart: always
    volumes:
     - ./config/conf.d:/etc/nginx/conf.d
     - ./config/nginx.conf:/etc/nginx/nginx.conf
     - ./tvGuide:/etc/nginx/tvGuide
     - ./ssl:/etc/nginx/ssl
    ports:
      - '8001:80'

volumes:
  dizquetv:
