version: '3.3'

services:
  dizquetv:
    image: kookster310/dizquetv-arm64:latest
    hostname: dizquetv
    restart: always
    volumes:
      - dizquetv:/opt/dizquetv
    ports:
      - '8000:8000'
      - '8001:8001'
    environment:
      - TVTIMEZONE=America\/New_York
      - LINEUPID=USA-OTA30236

volumes:
  dizquetv:
